import "./globals.css";
import type { Metadata } from "next";
import MainProvider from "./_providers/main/main.provider";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Cartera",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
