import {
  BadgePercent,
  Bike,
  Bitcoin,
  BrickWallFire,
  BriefcaseBusiness,
  BusFront,
  Cat,
  ChartLine,
  ChartNoAxesCombined,
  ChartSpline,
  CircleDollarSign,
  CircleHelp,
  CreditCard,
  DollarSign,
  Gift,
  GraduationCap,
  HandCoins,
  Handshake,
  HeartPulse,
  HelpCircle,
  House,
  HousePlug,
  HousePlus,
  HouseWifi,
  LampDesk,
  PartyPopper,
  PiggyBank,
  Receipt,
  Scale,
  Shirt,
  ShoppingBag,
  TreePalm,
  Utensils,
  UtilityPole,
  Wallet,
  WashingMachine,
} from "lucide-react";
import { ICON_SLUGS } from "@/domain/category/category.dto";
import { JSX } from "react";

const IconMap: Record<
  (typeof ICON_SLUGS)[keyof typeof ICON_SLUGS],
  React.ReactElement
> = {
  default: <CircleHelp size={22} />,
  "restaurantes-e-alimentacao": <Utensils size={22} />,
  supermercado: <Utensils size={22} />,
  "compras-e-lazer": <ShoppingBag size={22} />,
  "saude-e-bem-estar": <HeartPulse size={22} />,
  "eventos-e-festas": <PartyPopper size={22} />,
  "educacao-e-leitura": <GraduationCap size={22} />,
  "moradia-e-manutencao-residencial": <House size={22} />,
  "assinatura-de-internet-telefonia-e-streamings": <HouseWifi size={22} />,
  "servicos-e-utilidades-publicas": <UtilityPole size={22} />,
  "transporte-e-mobilidade": <BusFront size={22} />,
  "seguros-e-protecao": <BrickWallFire size={22} />,
  "vestuario-e-acessorios": <Shirt size={22} />,
  "viagens-e-turismo": <TreePalm size={22} />,
  "presentes-e-doacoes": <Gift size={22} />,
  "taxas-e-impostos": <DollarSign size={22} />,
  "cuidados-com-pets": <Cat size={22} />,
  "cuidados-com-dependentes": <Handshake size={22} />,
  "servicos-de-limpeza-e-lavanderia": <WashingMachine size={22} />,
  "despesas-de-negocios-e-escritorio": <LampDesk size={22} />,
  "tecnologia-e-software": <HousePlug size={22} />,
  "servicos-profissionais": <Scale size={22} />,
  "artigos-esportivos-e-hobbies": <Bike size={22} />,
  "despesa-com-cartao-de-credito": <CreditCard size={22} />,
  "consumos-diversos": <BriefcaseBusiness size={22} />,
  "salariopro-labore": <CircleDollarSign size={22} />,
  "recebimento-por-servico-prestado": <Receipt size={22} />,
  "alugueis-e-rendimentos-de-ativos": <HousePlus size={22} />,
  "investimentos-e-rendimentos-financeiros": <ChartNoAxesCombined size={22} />,
  "reembolsos-e-indenizacoes": <BadgePercent size={22} />,
  "comissoes-e-bonificacoes": <HandCoins size={22} />,
  "doacoes-e-herancas": <PiggyBank size={22} />,
  "aportes-e-financiamentos": <Bitcoin size={22} />,
  "receitas-de-parcerias-e-patrocinios": <ChartSpline size={22} />,
  "aposentadorias-e-pensoes": <Wallet size={22} />,
  "receitas-diversas": <ChartLine size={22} />,
};

export function resolveIcon(slug: string): JSX.Element {
  return (
    (IconMap as Record<string, JSX.Element>)[slug] ?? <HelpCircle size={22} />
  );
}
