name: Cartera-Frontend CI-CD

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: "🚀 Build & Test"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: true
    outputs:
      tests-passed: ${{ steps.unit-tests.outcome == 'success' }}
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Check origem do PR
        run: |
          echo BASE_BRANCH: "${{ github.base_ref }}"
          echo HEAD_BRANCH: "${{ github.head_ref }}"

          if [[ "${{ github.base_ref }}" == "main" && "${{ github.head_ref }}" != "dev" ]]; then
            echo "Erro: Apenas podem ser abertos PRs para branch MAIN a partir da branch DEV."
            exit 1
          fi

        shell: bash
        continue-on-error: false

      - name: Configuração do Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"


      - name: Instalando as dependências
        run: yarn install --frozen-lockfile

      - name: Verificando Lint
        run: yarn lint
        continue-on-error: false

      - name: Limpeza do cache do Jest
        run: npx jest --clearCache

      - name: Analisando Testes Unitários
        id: unit-tests
        run: yarn test:unit
        continue-on-error: false
